// UI language: translates interface chrome (buttons, headers, labels) only — the quiz
// questions/options themselves always stay in English, since that's the content being
// learned. Ported verbatim from the vanilla-JS version.

export const LEVEL_TRANSLATIONS = {
  a1: {
    en: { name: "Beginner", description: "Basic words, 'to be', simple present, everyday vocabulary." },
    ar: { name: "مبتدئ", description: "كلمات أساسية، فعل الكينونة، المضارع البسيط، مفردات يومية." },
  },
  a2: {
    en: { name: "Elementary", description: "Past simple, present continuous, comparatives, modals." },
    ar: { name: "أساسي", description: "الماضي البسيط، المضارع المستمر، صيغ المقارنة، الأفعال الناقصة." },
  },
  b1: {
    en: { name: "Intermediate", description: "Present perfect, conditionals, passive voice, phrasal verbs." },
    ar: { name: "متوسط", description: "المضارع التام، الجمل الشرطية، المبني للمجهول، الأفعال المركبة." },
  },
  b2: {
    en: { name: "Upper-Intermediate", description: "Second/third conditionals, deduction modals, collocations." },
    ar: { name: "فوق المتوسط", description: "الشرط الثاني والثالث، أفعال الاستنتاج، المتلازمات اللفظية." },
  },
};

export const STRINGS = {
  en: {
    appName: "HamoLingo",
    settings: "Settings",
    language: "Language",
    darkMode: "Dark Mode",
    cancel: "Cancel",
    confirmYes: "Yes, Start Over",
    menu: "Menu",
    close: "Close",
    switchToLight: "Switch to light mode",
    switchToDark: "Switch to dark mode",
    switchUiLang: "عربي",
    vocabulary: "Vocabulary",
    vocabularyTitle: (label) => `${label} Vocabulary`,
    vocabularySubtitle: (label) => `Browse core words from the ${label} level, with Arabic meanings and pronunciation.`,
    grammar: "Grammar",
    grammarTitle: (label) => `${label} Grammar`,
    grammarSubtitle: (label) => `Core grammar rules for the ${label} level, with examples and Arabic translations.`,
    grammarRuleLabel: "Rule",
    grammarExamplesLabel: "Examples",
    quizMe: "Quiz Me",
    vocabQuizNext: "Next Word",
    vocabQuizScore: (score, total) => `Score: ${score}/${total}`,
    missedTimes: (count) => `Missed ${count} time${count === 1 ? "" : "s"} recently`,
    exampleSentence: "Example Sentence",
    showTranslation: "Show Translation",
    stagesTitle: "Stages",
    stagesCompleteOf: (done, total) => `${done} / ${total} complete`,
    legendCurrent: "Current",
    legendDone: "Done",
    legendPerfect: "Perfect",
    legendLocked: "Locked",
    stageN: (n) => `Stage ${n}`,
    stageTitleScore: (n, score, size) => `Stage ${n} — ${score}/${size}`,
    stageTitleInProgress: (n, x, size) => `Stage ${n} — in progress (${x}/${size})`,
    stageTitleLocked: (n) => `Stage ${n} — locked`,
    subtitleQuestion: (stage, totalStages, q, stageSize, overall, total) =>
      `Stage ${stage} of ${totalStages} · Question ${q} of ${stageSize} · Overall ${overall}/${total}`,
    subtitleStageComplete: (stage, total) => `Stage ${stage} of ${total} complete`,
    subtitleReviewing: (stage) => `Reviewing Stage ${stage}`,
    subtitleQuizComplete: "Quiz complete",
    chooseLevel: "Choose your level",
    chooseLevelSubtitle: "Each level has 500 questions across 50 stages, with bilingual (English/Arabic) explanations.",
    notStarted: "Not started",
    inProgress: (a, b) => `In progress — ${a}/${b}`,
    completedScore: (a, b) => `Completed — ${a}/${b}`,
    listenToQuestion: "Listen to question",
    listenToOption: "Listen to option",
    correct: "Correct!",
    notQuite: "Not quite.",
    next: "Next",
    finish: "Finish",
    stageComplete: (n) => `Stage ${n} Complete!`,
    continueToStage: (n) => `Continue to Stage ${n}`,
    viewFinalResults: "View Final Results",
    stageReview: (n, score, size) => `Stage ${n} Review — ${score}/${size}`,
    yourAnswer: "Your answer:",
    correctAnswer: "Correct answer:",
    back: "Back",
    quizComplete: "Quiz Complete!",
    resultOutstanding: "Outstanding work!",
    resultGreat: "Great job!",
    resultGood: "Good effort — keep practicing!",
    resultKeepGoing: "Keep going, you'll get there!",
    takeQuizAgain: "Take Quiz Again",
    confirmStartOver: "Start over? This will erase your saved progress for this level.",
  },
  ar: {
    appName: "HamoLingo",
    settings: "الإعدادات",
    language: "اللغة",
    darkMode: "الوضع الداكن",
    cancel: "إلغاء",
    confirmYes: "نعم، ابدأ من جديد",
    menu: "القائمة",
    close: "إغلاق",
    switchToLight: "التبديل إلى الوضع الفاتح",
    switchToDark: "التبديل إلى الوضع الداكن",
    switchUiLang: "English",
    vocabulary: "المفردات",
    vocabularyTitle: (label) => `مفردات المستوى ${label}`,
    vocabularySubtitle: (label) => `تصفح الكلمات الأساسية لمستوى ${label}، مع معانيها بالعربية ونطقها.`,
    grammar: "القواعد",
    grammarTitle: (label) => `قواعد المستوى ${label}`,
    grammarSubtitle: (label) => `أهم قواعد اللغة لمستوى ${label}، مع أمثلة وترجمتها بالعربية.`,
    grammarRuleLabel: "القاعدة",
    grammarExamplesLabel: "أمثلة",
    quizMe: "اختبرني",
    vocabQuizNext: "الكلمة التالية",
    vocabQuizScore: (score, total) => `النتيجة: ${score}/${total}`,
    missedTimes: (count) => `أخطأت بها ${count} ${count === 1 ? "مرة" : "مرات"} مؤخرًا`,
    exampleSentence: "جملة توضيحية",
    showTranslation: "إظهار الترجمة",
    stagesTitle: "المراحل",
    stagesCompleteOf: (done, total) => `${done} / ${total} مكتملة`,
    legendCurrent: "الحالية",
    legendDone: "منتهية",
    legendPerfect: "ممتازة",
    legendLocked: "مغلقة",
    stageN: (n) => `المرحلة ${n}`,
    stageTitleScore: (n, score, size) => `المرحلة ${n} — ${score}/${size}`,
    stageTitleInProgress: (n, x, size) => `المرحلة ${n} — قيد التقدم (${x}/${size})`,
    stageTitleLocked: (n) => `المرحلة ${n} — مغلقة`,
    subtitleQuestion: (stage, totalStages, q, stageSize, overall, total) =>
      `المرحلة ${stage} من ${totalStages} · السؤال ${q} من ${stageSize} · الإجمالي ${overall}/${total}`,
    subtitleStageComplete: (stage, total) => `اكتملت المرحلة ${stage} من ${total}`,
    subtitleReviewing: (stage) => `مراجعة المرحلة ${stage}`,
    subtitleQuizComplete: "اكتمل الاختبار",
    chooseLevel: "اختر مستواك",
    chooseLevelSubtitle: "يحتوي كل مستوى على 500 سؤال موزعة على 50 مرحلة، مع شروحات ثنائية اللغة (إنجليزي/عربي).",
    notStarted: "لم يبدأ",
    inProgress: (a, b) => `قيد التقدم — ${a}/${b}`,
    completedScore: (a, b) => `مكتمل — ${a}/${b}`,
    listenToQuestion: "استمع إلى السؤال",
    listenToOption: "استمع إلى الخيار",
    correct: "إجابة صحيحة!",
    notQuite: "ليست صحيحة تماماً.",
    next: "التالي",
    finish: "إنهاء",
    stageComplete: (n) => `اكتملت المرحلة ${n}!`,
    continueToStage: (n) => `المتابعة إلى المرحلة ${n}`,
    viewFinalResults: "عرض النتيجة النهائية",
    stageReview: (n, score, size) => `مراجعة المرحلة ${n} — ${score}/${size}`,
    yourAnswer: "إجابتك:",
    correctAnswer: "الإجابة الصحيحة:",
    back: "رجوع",
    quizComplete: "اكتمل الاختبار!",
    resultOutstanding: "أداء رائع!",
    resultGreat: "عمل ممتاز!",
    resultGood: "جهد جيد — واصل التدرب!",
    resultKeepGoing: "واصل التقدم، ستصل قريباً!",
    takeQuizAgain: "أعد الاختبار",
    confirmStartOver: "هل تريد البدء من جديد؟ سيتم حذف تقدمك المحفوظ لهذا المستوى.",
  },
};
